apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devops

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:

      - name: frontend
        image: chritik24/devops-frontend:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"

          limits:
            cpu: "200m"
            memory: "256Mi"

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
