apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: backend-alerts
  namespace: monitoring
  labels:
    release: monitoring

spec:
  groups:
    - name: backend.rules

      rules:
        - alert: BackendDown

          expr: kube_deployment_status_replicas_available{deployment="backend",namespace="devops"} < 1

          for: 1m

          labels:
            severity: critical

          annotations:
            summary: "Backend Deployment Down"
            description: "Backend deployment has no available replicas."
